name: Spacebattle
version: '${project.version}'
main: server18_2.spacebattle.Main
api-version: 1.18
authors: [Surprise432, Roger-15]
commands:
  shildcristal:
    description: shildcristal command
    aliases: sc
    usage: "Usage: /sc <set|reset> <game> <team>"
  shields:
    description: shields command
    usage: "Usage: /<command> get <game> <team> OR /<command> <set|hit> <front|left|right|back> <game> <team> OR /<command> <addconverter> OR /<command> <removeconverter> <converter>"
  teleportpad:
    description: teleport pad command
    aliases: tpp
    usage: "Usage: /tpp add <position xyz> OR /tpp remove"
  spacebattle:
    description: spacebattle command
    aliases: sb
    usage: "Usage: /<command> add <number of teams> OR /<command> remove <index>"